# Generated by Django 5.1.3 on 2025-01-03 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0004_rename_fullname_user_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='username',
            new_name='fullname',
        ),
    ]
