# Generated by Django 5.1.3 on 2025-01-03 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_username_user_fullname'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='user',
            managers=[
            ],
        ),
    ]
