# Generated by Django 5.1.3 on 2025-01-04 11:47

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_remove_otp_exprision_date_otp_expires_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='otp',
            name='expires_at',
        ),
        migrations.AddField(
            model_name='otp',
            name='exprision_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='otp',
            name='code',
            field=models.SmallIntegerField(),
        ),
        migrations.AlterField(
            model_name='otp',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(max_length=11),
        ),
        migrations.AlterField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
