# Generated by Django 5.1.3 on 2025-01-12 10:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_otp_exprision_date_alter_otp_code_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='fullname',
            new_name='username',
        ),
    ]
