# Generated by Django 5.1.3 on 2025-01-19 19:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0016_alter_profile_options_alter_profile_about_me_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100, verbose_name='نام')),
                ('last_name', models.CharField(max_length=100, verbose_name='نام خانوادگی')),
                ('province', models.CharField(max_length=100, verbose_name='استان')),
                ('city', models.CharField(max_length=100, verbose_name='شهر')),
                ('street', models.CharField(max_length=255, verbose_name='خیابان')),
                ('building_info', models.CharField(max_length=255, verbose_name='اطلاعات ساختمان')),
                ('phone', models.CharField(max_length=15, verbose_name='تلفن')),
                ('post_code', models.CharField(max_length=10, verbose_name='کد پستی')),
                ('mail_ticket', models.TextField(blank=True, null=True, verbose_name='توضیحات اضافی')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to=settings.AUTH_USER_MODEL, verbose_name='کاربر')),
            ],
            options={
                'verbose_name': 'آدرس کاربر',
                'verbose_name_plural': 'آدرس\u200cهای کاربران',
            },
        ),
    ]
