# Generated by Django 5.1.3 on 2025-01-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0017_useraddress'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserAddress',
        ),
    ]
