# Generated by Django 5.1.3 on 2025-01-19 19:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0002_delete_blog'),
    ]

    operations = [
        migrations.CreateModel(
            name='CategoryBlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=288, verbose_name='نام دسته بندی')),
            ],
            options={
                'verbose_name': 'دسته بندی بلاگ',
                'verbose_name_plural': 'دسته بندی های بلاگ',
            },
        ),
        migrations.CreateModel(
            name='BlogPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان بلاگ')),
                ('image', models.ImageField(upload_to='blog/images/', verbose_name='تصویر بلاگ')),
                ('content', models.TextField(verbose_name='محتوای بلاگ')),
                ('publish_date', models.DateField(verbose_name='تاریخ انتشار')),
                ('slug', models.SlugField(unique=True, verbose_name='آدرس بلاگ')),
                ('Introduction', models.TextField(blank=True, null=True, verbose_name='معرفی')),
                ('Introduction_tow', models.TextField(blank=True, null=True, verbose_name='معرفی دو')),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blogs', to='blog.categoryblog', verbose_name='دسته بندی')),
            ],
            options={
                'verbose_name': 'پست بلاگ',
                'verbose_name_plural': 'پست های بلاگ',
            },
        ),
    ]
