# Generated by Django 5.1.3 on 2025-01-19 19:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BlogPost',
        ),
        migrations.DeleteModel(
            name='CategoryBlog',
        ),
    ]
